Mxonline/urls.py
from django.conf.urls import url,include
from extra_apps import xadmin
from django.conf.urls.static import static
from django.conf import settings
from django.views.static import serve

from users.views import IndexView

urlpatterns = [
    url(r'^xadmin/', xadmin.site.urls),
    url(r'^captcha/', include('captcha.urls')),
    url(r'^users/', include('users.urls',namespace='users')),
    #配置上传文件的访问处理函数
    # url(r'^media/(?P<path>.*)$', serve, {"document_root": settings.MEDIA_ROOT}),
    url(r'org/', include('organization.urls',namespace='organization')),
    url(r'course/', include('courses.urls',namespace='course')),
    url(r'^$', IndexView.as_view(), name='index'),
    ]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/organization/urls.py
from django.conf.urls import url

from .views import OrgView,AddUserAskView,OrgHomeView,OrgCourseView,OrgDescView,OrgTeacherView,TeacherListView,TeacherDetailView,AddFavView
# from .views import PasswordUploadView

urlpatterns = [
    url(r'^org_list/$',OrgView.as_view(),name='org_list'),
    url(r'^add_ask/$',AddUserAskView.as_view(),name='add_ask'),
    url(r'^add/fav/$',AddFavView.as_view(),name='add_fav'),
    url(r'^org_home/(?P<org_id>\d+)$',OrgHomeView.as_view(),name='org_home'),
    url(r'^org_course/(?P<org_id>\d+)$',OrgCourseView.as_view(),name='org_course'),
    url(r'^org_desc/(?P<org_id>\d+)$',OrgDescView.as_view(),name='org_desc'),
    url(r'^org_teacher/(?P<org_id>\d+)$',OrgTeacherView.as_view(),name='org_teacher'),
    url(r'^teacher/list/$',TeacherListView.as_view(),name='teacher_list'),
    url(r'^teacher/detail/(?P<teacher_id>\d+)$',TeacherDetailView.as_view(),name='teacher_detail'),
]

apps/users/urls.py
from django.conf.urls import url
from django.contrib.sessions.middleware import SessionMiddleware

from .views import IndexView,UserInfoView,ImageUploadView,LoginView,LogoutView,RegisterView,PasswordForgetView,PasswordResetView,EmailVerifyView,ModifyPwdView
# from .views import PasswordUploadView

urlpatterns = [
    url(r'^info/$',UserInfoView.as_view(),name='info'),
    url(r'^image/upload/$',IndexView.as_view(),name='image_upload'),
    url(r'^reset/password/$', IndexView.as_view(), name='reset_password'),
    url(r'^mycourse',IndexView.as_view(),name='mycourse'),
    url(r'^fav/course',IndexView.as_view(),name='fav_course'),
    url(r'^mymessage',IndexView.as_view(),name='mymessage'),

    url(r'^register/$', RegisterView.as_view(), name='register'),
    url(r'^login/$', LoginView.as_view(), name='login'),
    url(r'^logout/$', LogoutView.as_view(), name='logout'),
    url(r'^forget-password/$', PasswordForgetView.as_view(), name='forget_password'),
    url(r'^email-verify/(?P<verify_record>\w+)', EmailVerifyView.as_view(), name='email_verify'),
    url(r'^modify-password/$', ModifyPwdView.as_view(), name='modify_password'),
]

extra_apps/xadmin/views/base.py
import copy
import functools
import datetime
import decimal
from functools import update_wrapper
from inspect import getargspec

from django import forms
from django.apps import apps
from django.conf import settings
from django.contrib import messages
from django.contrib.auth import get_permission_codename
from django.core.exceptions import ValidationError
from django.core.serializers.json import DjangoJSONEncoder
from django.core.urlresolvers import reverse
from django.http import HttpResponse
from django.template import Context, Template
from django.template.response import TemplateResponse
from django.utils import six
from django.utils.decorators import method_decorator, classonlymethod
from django.utils.encoding import force_text, smart_text, smart_str
from django.utils.functional import Promise
from django.utils.http import urlencode
from django.utils.itercompat import is_iterable
from django.utils.safestring import mark_safe
from django.utils.text import capfirst
from django.utils.translation import ugettext as _
from django.views.decorators.csrf import csrf_protect
from django.views.generic import View
from collections import OrderedDict
from xadmin.util import static, json, vendor, sortkeypicker

from xadmin.models import Log

csrf_protect_m = method_decorator(csrf_protect)


class IncorrectPluginArg(Exception):
    pass

def get_content_type_for_model(obj):
    from django.contrib.contenttypes.models import ContentType
    return ContentType.objects.get_for_model(obj, for_concrete_model=False)

def filter_chain(filters, token, func, *args, **kwargs):
    if token == -1:
        return func()
    else:
        def _inner_method():
            fm = filters[token]
            fargs = getargspec(fm)[0]
            if len(fargs) == 1:
                # Only self arg
                result = func()
                if result is None:
                    return fm()
                else:
                    raise IncorrectPluginArg(u'Plugin filter method need a arg to receive parent method result.')
            else:
                return fm(func if fargs[1] == '__' else func(), *args, **kwargs)
        return filter_chain(filters, token - 1, _inner_method, *args, **kwargs)


def filter_hook(func):
    tag = func.__name__
    func.__doc__ = "``filter_hook``\n\n" + (func.__doc__ or "")

    @functools.wraps(func)
    def method(self, *args, **kwargs):

        def _inner_method():
            return func(self, *args, **kwargs)

        if self.plugins:
            filters = [(getattr(getattr(p, tag), 'priority', 10), getattr(p, tag))
                       for p in self.plugins if callable(getattr(p, tag, None))]
            filters = [f for p, f in sorted(filters, key=lambda x:x[0])]
            return filter_chain(filters, len(filters) - 1, _inner_method, *args, **kwargs)
        else:
            return _inner_method()
    return method


def inclusion_tag(file_name, context_class=Context, takes_context=False):
    def wrap(func):
        @functools.wraps(func)
        def method(self, context, nodes, *arg, **kwargs):
            _dict = func(self, context, nodes, *arg, **kwargs)
            from django.template.loader import get_template, select_template
            cls_str = str if six.PY3 else basestring
            if isinstance(file_name, Template):
                t = file_name
            elif not isinstance(file_name, cls_str) and is_iterable(file_name):
                t = select_template(file_name)
            else:
                t = get_template(file_name)

            _dict['autoescape'] = context.autoescape
            _dict['use_l10n'] = context.use_l10n
            _dict['use_tz'] = context.use_tz
            _dict['admin_view'] = context['admin_view']

            csrf_token = context.get('csrf_token', None)
            if csrf_token is not None:
                _dict['csrf_token'] = csrf_token
            nodes.append(t.render(_dict))

        return method
    return wrap


class JSONEncoder(DjangoJSONEncoder):
    def default(self, o):
        if isinstance(o, datetime.datetime):
            return o.strftime('%Y-%m-%d %H:%M:%S')
        elif isinstance(o, datetime.date):
            return o.strftime('%Y-%m-%d')
        elif isinstance(o, decimal.Decimal):
            return str(o)
        elif isinstance(o, Promise):
            return force_text(o)
        else:
            try:
                return super(JSONEncoder, self).default(o)
            except Exception:
                return smart_text(o)


class BaseAdminObject(object):

    def get_view(self, view_class, option_class=None, *args, **kwargs):
        opts = kwargs.pop('opts', {})
        return self.admin_site.get_view_class(view_class, option_class, **opts)(self.request, *args, **kwargs)

    def get_model_view(self, view_class, model, *args, **kwargs):
        return self.get_view(view_class, self.admin_site._registry.get(model), *args, **kwargs)

    def get_admin_url(self, name, *args, **kwargs):
        return reverse('%s:%s' % (self.admin_site.app_name, name), args=args, kwargs=kwargs)

    def get_model_url(self, model, name, *args, **kwargs):
        return reverse(
            '%s:%s_%s_%s' % (self.admin_site.app_name, model._meta.app_label,
                             model._meta.model_name, name),
            args=args, kwargs=kwargs, current_app=self.admin_site.name)

    def get_model_perm(self, model, name):
        return '%s.%s_%s' % (model._meta.app_label, name, model._meta.model_name)

    def has_model_perm(self, model, name, user=None):
        user = user or self.user
        return user.has_perm(self.get_model_perm(model, name)) or (name == 'view' and self.has_model_perm(model, 'change', user))

    def get_query_string(self, new_params=None, remove=None):
        if new_params is None:
            new_params = {}
        if remove is None:
            remove = []
        p = dict(self.request.GET.items()).copy()
        arr_keys = list(p.keys())
        for r in remove:
            for k in arr_keys:
                if k.startswith(r):
                    del p[k]
        for k, v in new_params.items():
            if v is None:
                if k in p:
                    del p[k]
            else:
                p[k] = v
        return '?%s' % urlencode(p)

    def get_form_params(self, new_params=None, remove=None):
        if new_params is None:
            new_params = {}
        if remove is None:
            remove = []
        p = dict(self.request.GET.items()).copy()
        arr_keys = list(p.keys())
        for r in remove:
            for k in arr_keys:
                if k.startswith(r):
                    del p[k]
        for k, v in new_params.items():
            if v is None:
                if k in p:
                    del p[k]
            else:
                p[k] = v
        return mark_safe(''.join(
            '<input type="hidden" name="%s" value="%s"/>' % (k, v) for k, v in p.items() if v))

    def render_response(self, content, response_type='json'):
        if response_type == 'json':
            response = HttpResponse(content_type="application/json; charset=UTF-8")
            response.write(
                json.dumps(content, cls=JSONEncoder, ensure_ascii=False))
            return response
        return HttpResponse(content)

    def template_response(self, template, context):
        return TemplateResponse(self.request, template, context)

    def message_user(self, message, level='info'):
        """
        Send a message to the user. The default implementation
        posts a message using the django.contrib.messages backend.
        """
        if hasattr(messages, level) and callable(getattr(messages, level)):
            getattr(messages, level)(self.request, message)

    def static(self, path):
        return static(path)

    def vendor(self, *tags):
        return vendor(*tags)

    def log(self, flag, message, obj=None):
        log = Log(
            user=self.user, 
            ip_addr=self.request.META['REMOTE_ADDR'],
            action_flag=flag,
            message=message
        )
        if obj:
            log.content_type = get_content_type_for_model(obj)
            log.object_id = obj.pk
            log.object_repr = force_text(obj)
        log.save()


class BaseAdminPlugin(BaseAdminObject):

    def __init__(self, admin_view):
        self.admin_view = admin_view
        self.admin_site = admin_view.admin_site

        if hasattr(admin_view, 'model'):
            self.model = admin_view.model
            self.opts = admin_view.model._meta

    def init_request(self, *args, **kwargs):
        pass


class BaseAdminView(BaseAdminObject, View):
    """ Base Admin view, support some comm attrs."""

    base_template = 'xadmin/base.html'
    need_site_permission = True

    def __init__(self, request, *args, **kwargs):
        self.request = request
        self.request_method = request.method.lower()
        self.user = request.user
        
        self.base_plugins = [p(self) for p in getattr(self,
                                                      "plugin_classes", [])]

        self.args = args
        self.kwargs = kwargs
        self.init_plugin(*args, **kwargs)
        self.init_request(*args, **kwargs)

    @classonlymethod
    def as_view(cls):
        def view(request, *args, **kwargs):
            self = cls(request, *args, **kwargs)

            if hasattr(self, 'get') and not hasattr(self, 'head'):
                self.head = self.get

            if self.request_method in self.http_method_names:
                handler = getattr(
                    self, self.request_method, self.http_method_not_allowed)
            else:
                handler = self.http_method_not_allowed

            return handler(request, *args, **kwargs)

        # take name and docstring from class
        update_wrapper(view, cls, updated=())
        view.need_site_permission = cls.need_site_permission

        return view

templates/email-send.html
{% load staticfiles %}
<!DOCTYPE html>
<html>

<head>
    <meta charset="UTF-8">
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <title>邮件发送成功</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/login.css' %}">
</head>
<body>
<header>
    <div class="c-box fff-box">
        <div class="wp header-box">
            <p class="fl hd-tips">慕学在线网，在线学习平台！</p>
            <ul class="fr hd-bar">
                <li>服务电话：<span>33333333</span></li>
                <li class="active"><a href="{% url 'users:login' %}">[登录]</a></li>
                <li><a href="{% url 'users:register' %}">[注册]</a></li>
            </ul>
        </div>
    </div>
</header>
<section>
    <div class="c-box bg-box">
        <div class="login-box clearfix">
            <div class="hd-login clearfix">
                <a class="index-logo" href="{% url 'users:login' %}"></a>
                <h1>邮件验证提示</h1>
                <a class="index-font" href="{% url 'index' %}">回到首页</a>
            </div>
            <div class="fl form-box" style="width: 790px">
                <br class="center">
                <img src="{% static 'images/send.png' %}"/>
                {% if send_status %}
                    <p style="font-size: 18px">我们已经向您的邮箱<span class="green" id="jsEmailToActive">{{ email }}</span>发送了邮件，为保证您的账号安全，请及时查看邮箱。
                    </p><br>
                    <p style="font-size: 18px">如果没收到，您可以查看您的垃圾邮件和被过滤邮件，也可以再次发送验证邮件</p>
                {% else %}
                    <p style="font-size: 18px">发送失败,请查看邮箱是否输入正确并重新<a href="{% url 'users:register' %}">注册</a></p>
                {% endif %}
            </div>
        </div>
    </div>
</section>
<script src="{% static 'js/jquery.min.js' %}" type="text/javascript"></script>
<script src="{% static 'js/unslider.js' %}" type="text/javascript"></script>
<script src="{% static 'js/login.js' %}" type="text/javascript"></script>
</body>
</html>

templates/email-verify.html
{% load staticfiles %}
<!DOCTYPE html>
<html>

<head>
    <meta charset="UTF-8">
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <title>链接验证</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/login.css' %}">
</head>
<body>
<header>
    <div class="c-box fff-box">
        <div class="wp header-box">
            <p class="fl hd-tips">慕学在线网，在线学习平台！</p>
            <ul class="fr hd-bar">
                <li>服务电话：<span>33333333</span></li>
                <li class="active"><a href="{% url 'users:login' %}">[登录]</a></li>
                <li><a href="{% url 'users:register' %}">[注册]</a></li>
            </ul>
        </div>
    </div>
</header>
<section>
    <div class="c-box bg-box">
        <div class="login-box clearfix">
            <div class="hd-login clearfix">
                <a class="index-logo" href="{% url 'users:login' %}"></a>
                <h1>邮件验证提示</h1>
                <a class="index-font" href="{% url 'index' %}">回到首页</a>
            </div>
            <div class="fl form-box" style="width: 790px">
                <br class="center">
                {% if verify_status %}
                    <p style="font-size: 18px">邮箱验证成功，可以前往<a style="color: blue" href="{% url 'users:login' %}">登录</a></p>
                {% else %}
                    <p style="font-size: 18px">该链接失效,请重新<a style="color: blue" href="{% url 'users:register' %} ">注册</a></p>
                {% endif %}
            </div>
        </div>
    </div>
</section>
<script src="{% static 'js/jquery.min.js' %}" type="text/javascript"></script>
<script src="{% static 'js/unslider.js' %}" type="text/javascript"></script>
<script src="{% static 'js/login.js' %}" type="text/javascript"></script>
</body>
</html>

templates/forgetpwd.html
{% load staticfiles %}
<!DOCTYPE html>
<html>

<head>
	<meta charset="UTF-8">
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1" >
	<title>忘记密码</title>
	<link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/login.css' %}">
</head>
<body>
<header>
    <div class="c-box fff-box">
        <div class="wp header-box">
            <p class="fl hd-tips">慕学网，在线学习平台！</p>
            <ul class="fr hd-bar">
                <li>服务电话：<span>33333333</span></li>
                <li><a href="{% url 'users:login' %}">[登录]</a></li>
                <li class="active"><a href="{% url 'users:forget_password' %}">[忘记密码]</a></li>
            </ul>
        </div>
    </div>
</header>
<section>
    <div class="c-box bg-box">
        <div class="login-box clearfix">
            <div class="hd-login clearfix">
                <a class="index-logo" href="{% url 'users:forget_password' %}"></a>
                <h1>忘记密码</h1>
                <a class="index-font" href="{% url 'index' %}">回到首页</a>
            </div>
            <div class="fl slide">
                <div class="imgslide">
                    <ul class="imgs">
                        <li><a href=""><img width="483" height="472" src="{% static 'images/57a801860001c34b12000460.jpg' %}" /></a></li>
                        <li><a href=""><img width="483" height="472" src="{% static 'images/57a801860001c34b12000460.jpg' %}" /></a></li>
                        <li><a href=""><img width="483" height="472" src="{% static 'images/57a801860001c34b12000460.jpg' %}" /></a></li>
                    </ul>
                </div>
                <div class="unslider-arrow prev"></div>
                <div class="unslider-arrow next"></div>
            </div>
            <div class="fl form-box">
                <h2>忘记密码</h2>
                <form id="jsFindPwdForm" method="post" action="{% url 'users:forget_password' %}" autocomplete="off">
                    <div class="form-group marb20 ">
                        <label>帐&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;号</label>
                        <input type="text" id="account" name="email" value="1045602705@qq.com" placeholder="邮箱" />
                    </div>
                    <div class="form-group captcha1 marb38">
                        <label>验&nbsp;证&nbsp;码</label>
                        {{ forget_form.captcha }}
                    </div>
                    <div class="error btns" id="jsForgetTips">{{ error_message }}{% for key,value in forget_form.errors.items %}{{ value }}{% endfor %}</div>
                    <input type="hidden" name="sms_type" value="1">
                    <input class="btn btn-green" id="jsFindPwdBtn" type="submit" value="提交" />
                    <p class="form-p" style="bottom:40px;">您还可以<a href="{% url 'users:login' %}"> [直接登录]</a></p>
                    {% csrf_token %}
                </form>
            </div>
        </div>
    </div>
</section>

<script src="{% static 'js/jquery.min.js' %}" type="text/javascript"></script>
<script src="{% static 'js/unslider.js' %}" type="text/javascript"></script>
<script src="{% static 'js/validateDialog.js' %}" type="text/javascript"></script>
<script src="{% static 'js/login.js' %}" type="text/javascript"></script>
</body>
</html>

templates/password-modify.html
{% load staticfiles %}
<!DOCTYPE html>
<html>

<head>
    <meta charset="UTF-8">
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <title>密码重置</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/login.css' %}">
</head>
<body>
<header>
    <div class="c-box fff-box">
        <div class="wp header-box">
            <p class="fl hd-tips">慕学在线网，在线学习平台！</p>
            <ul class="fr hd-bar">
                <li>服务电话：<span>33333333</span></li>
                <li class="active"><a href="{% url 'users:login' %}">[登录]</a></li>
                <li><a href="{% url 'users:register' %}">[注册]</a></li>
            </ul>
        </div>
    </div>
</header>
<section>
    <div class="c-box bg-box">
        <div class="login-box clearfix">
            <div class="hd-login clearfix">
                <a class="index-logo" href="{% url 'users:login' %}"></a>
                <h1>修改密码</h1>
                <a class="index-font" href="{% url 'index' %}">回到首页</a>
            </div>
        {% if password_modify_status %}
            <div class="fl form-box" style="width: 790px">
                <br class="center">
                <p style="font-size: 18px">密码成功，可以前往<a style="color: blue" href="{% url 'users:login' %}">登录</a></p>
            </div>
        {% else %}
            <div class="fl slide">
                <div class="imgslide">
                    <ul class="imgs">
                        <li><a href=""><img width="483" height="472" src="{% static 'images/mysql.jpg' %}"/></a></li>
                        <li><a href=""><img width="483" height="472" src="{% static 'images/mysql.jpg' %}"/></a></li>
                        <li><a href=""><img width="483" height="472" src="{% static 'images/mysql.jpg' %}"/></a></li>
                    </ul>
                </div>
                <div class="unslider-arrow prev"></div>
                <div class="unslider-arrow next"></div>
            </div>
            <div class="fl form-box">
                <h2>修改密码</h2>
                <form action="{% url 'users:modify_password' %}" method="post" autocomplete="off">
                    {% csrf_token %}
					<input type="hidden" name="email" value="{{ email }}">
                    <div class="form-group marb20 {% if passwordmodify_form.errors.password_new1 %} errorput {% endif %}">
                        <label>新&nbsp;密&nbsp;码</label>
                        <input name="password_new1" id="password_l" type="password" placeholder="请输入密码"/>
                    </div>
                    <div class="form-group marb8 {% if passwordmodify_form.errors.password_new2 %} errorput {% endif %}">
                        <label>新&nbsp;密&nbsp;码</label>
                        <input name="password_new2" id="password_2" type="password" placeholder="请再次输入您的密码"/>
                    </div>
                    <div class="error btns login-form-tips" id="jsLoginTips">{% for key,value in login_form.errors.items %}{{ value }}{% endfor %}{{ msg }}</div>
                    <input class="btn btn-green" id="jsLoginBtn" type="submit" value="立即修改 > "/>
                </form>
            </div>
        {% endif %}
        </div>
    </div>
</section>
<script src="{% static 'js/jquery.min.js' %}" type="text/javascript"></script>
<script src="{% static 'js/unslider.js' %}" type="text/javascript"></script>
<script src="{% static 'js/login.js' %}" type="text/javascript"></script>
</body>
</html>

templates/password_reset.html
{% load staticfiles %}
<!DOCTYPE html>
<html>

<head>
    <meta charset="UTF-8">
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <title>密码重置</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/login.css' %}">
</head>
<body>
<header>
    <div class="c-box fff-box">
        <div class="wp header-box">
            <p class="fl hd-tips">慕学在线网，在线学习平台！</p>
            <ul class="fr hd-bar">
                <li>服务电话：<span>33333333</span></li>
                <li class="active"><a href="{% url 'users:login' %}">[登录]</a></li>
                <li><a href="{% url 'users:register' %}">[注册]</a></li>
            </ul>
        </div>
    </div>
</header>
<section>
    <div class="c-box bg-box">
        <div class="login-box clearfix">
            <div class="hd-login clearfix">
                <a class="index-logo" href="{% url 'users:login' %}"></a>
                <h1>修改密码</h1>
                <a class="index-font" href="{% url 'index' %}">回到首页</a>
            </div>
        {% if password_modify_status %}
            <div class="fl form-box" style="width: 790px">
                <br class="center">
                <p style="font-size: 18px">密码成功，可以前往<a style="color: blue" href="{% url 'users:login' %}">登录</a></p>
            </div>
        {% else %}
            <div class="fl slide">
                <div class="imgslide">
                    <ul class="imgs">
                        <li><a href=""><img width="483" height="472" src="{% static 'images/mysql.jpg' %}"/></a></li>
                        <li><a href=""><img width="483" height="472" src="{% static 'images/mysql.jpg' %}"/></a></li>
                        <li><a href=""><img width="483" height="472" src="{% static 'images/mysql.jpg' %}"/></a></li>
                    </ul>
                </div>
                <div class="unslider-arrow prev"></div>
                <div class="unslider-arrow next"></div>
            </div>
            <div class="fl form-box">
                <h2>修改密码</h2>
                <form action="{% url 'users:reset_password' %}" method="post" autocomplete="off">
                    {% csrf_token %}
					<input type="hidden" name="email" value="{{ email }}">
                    <div class="form-group marb20 {% if passwordreset_form.errors.password_old %} errorput {% endif %}">
                        <label>旧&nbsp;密&nbsp;码</label>
                        <input name="password_old" id="password_l" type="password" placeholder="请输入旧新密码"/>
                    </div>
                    <div class="form-group marb20 {% if passwordreset_form.errors.password_new1 %} errorput {% endif %}">
                        <label>新&nbsp;密&nbsp;码</label>
                        <input name="password_new1" id="password_2" type="password" placeholder="请输入密码"/>
                    </div>
                    <div class="form-group marb8 {% if passwordmodify_form.errors.password_new2 %} errorput {% endif %}">
                        <label>新&nbsp;密&nbsp;码</label>
                        <input name="password_new2" id="password_3" type="password" placeholder="请再次输入您的新密码"/>
                    </div>
                    <div class="error btns login-form-tips" id="jsLoginTips">{% for key,value in login_form.errors.items %}{{ value }}{% endfor %}{{ msg }}</div>
                    <input class="btn btn-green" id="jsLoginBtn" type="submit" value="立即修改 > "/>
                </form>
            </div>
        {% endif %}
        </div>
    </div>
</section>
<script src="{% static 'js/jquery.min.js' %}" type="text/javascript"></script>
<script src="{% static 'js/unslider.js' %}" type="text/javascript"></script>
<script src="{% static 'js/login.js' %}" type="text/javascript"></script>
</body>
</html>